"""
Django settings for demo_project.

Generated by the setup_guide.py learning script.
For the full settings reference, see:
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / "subdir".
# BASE_DIR points to the directory containing manage.py.
# Path(__file__).resolve() gets the absolute path of this settings file,
# then .parent.parent goes up two directories to the project root.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
# This key is used for cryptographic signing (sessions, CSRF tokens, etc.).
# In production, load this from an environment variable — never commit it.
SECRET_KEY = "django-insecure-learning-key-do-not-use-in-production"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG=True shows detailed error pages with stack traces and variable values.
# In production, set this to False so users see a generic error page instead.
DEBUG = True

# A list of hostnames/domains this Django site can serve.
# With DEBUG=True, Django allows localhost automatically.
# In production, add your domain: ["mysite.com", "www.mysite.com"]
ALLOWED_HOSTS = []

# ----------------------------------------------------------------
# INSTALLED_APPS: Every Django app must be listed here to be active.
#
# Django comes with several built-in apps:
# - admin: the /admin interface for managing database objects
# - auth: user accounts, passwords, permissions, groups
# - contenttypes: tracks which models exist (used internally)
# - sessions: server-side session storage for logged-in users
# - messages: one-time notification messages (e.g., "Item saved!")
# - staticfiles: serves CSS, JS, and images during development
#
# Your own apps go at the end of this list.
# ----------------------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Add your apps here, e.g.:
    "catalog.apps.CatalogConfig",
]

# ----------------------------------------------------------------
# MIDDLEWARE: A pipeline that processes every request and response.
#
# Each middleware is a layer. Requests pass through them top to bottom,
# and responses pass back bottom to top. Order matters.
# ----------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ROOT_URLCONF tells Django which file contains the top-level URL patterns.
# Django starts here and follows includes to find the right view for each URL.
ROOT_URLCONF = "demo_project.urls"

# ----------------------------------------------------------------
# TEMPLATES: How Django finds and renders HTML templates.
#
# DIRS: extra directories to search for templates (besides app directories).
# APP_DIRS: if True, Django looks in each app's templates/ subdirectory.
# ----------------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI_APPLICATION points to the WSGI callable for deployment.
# WSGI (Web Server Gateway Interface) is the standard for Python web apps.
WSGI_APPLICATION = "demo_project.wsgi.application"

# ----------------------------------------------------------------
# DATABASES: Where your data lives.
#
# By default, Django uses SQLite — a file-based database that
# requires zero setup. The database file (db.sqlite3) appears in
# your project root after running migrate.
#
# For production, you would switch to PostgreSQL or MySQL.
# ----------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation rules. These prevent weak passwords.
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization settings.
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True    # Enable Django's translation system
USE_TZ = True      # Store datetimes in UTC in the database

# Static files (CSS, JavaScript, Images).
# STATIC_URL is the URL prefix for static files.
# In development, Django serves them automatically.
STATIC_URL = "static/"

# Default primary key field type for models.
# BigAutoField creates an auto-incrementing 64-bit integer.
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
